import Head from 'next/head'
import {Work, WorkDataType} from '../../types'
import {Layout} from '../../components/layout'
import {Header} from '../../components/header'
import {Article} from '../../components/article'
import {Sidebar} from '../../components/sidebar'
import {Footer} from '../../components/footer'
import { getAllWorkIds, getWorkDataAndContent, getWorksData } from '../../lib/works'
import { areSimilar } from '../../lib/utils'

type Props = {
  item: Work
  similarItems: WorkDataType[]
}

const Work =  ({item, similarItems}: Props) => {
  return (
    <Layout className='bg-mute'>
      <Head>
        <title>{item.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/global-images/favicon.png" />
      </Head>
      <Header mode="light" />
      <div className='container py-36 lg:grid lg:grid-cols-3 lg:gap-16'>
        <Article item={item} />
        <Sidebar items={similarItems} />
      </div>
      <Footer position='static' />
    </Layout>
  )
}

export default Work

export const getStaticPaths = async () => {
  const paths = getAllWorkIds()
  return {
    paths,
    fallback: false
  }
}

export const getStaticProps = async ({params}: any) => {
  const item = await getWorkDataAndContent(params.id)
  // get all items except the currently displayed one
  const allOtherItems = getWorksData().filter(workData => workData.id !== params.id)
  // from all other items, get ones that share at least one tag with the current one
  const similarItems = allOtherItems.filter(workData => areSimilar(workData.tags, item.tags))
  return {
    props: {
      item,
      similarItems
    }
  }
}