import React, {useState, useEffect} from 'react'
import Head from 'next/head'
import {useRouter} from 'next/router'
import {GetStaticProps} from 'next'
import {WorkDataType} from '../../types';
import {getWorksData} from '../../lib/works'
import {getNumOfPages} from '../../lib/utils'
import {Layout} from '../../components/layout'
import {Header} from '../../components/header'
import {Main} from '../../components/main'
import {Card} from '../../components/card'
import {FilterButton} from '../../components/filterButton'
import {Pagination} from '../../components/pagination'
import {Footer} from '../../components/footer'

type Props = {
  worksData: WorkDataType[]
}

const FILTERVALUES = {
  ALL: "#all",
  APPS: "#app",
  LOGOS: "#logo",
  ILLUSTRATIONS: "#illustration",
}

const ITEMPERPAGE = 2

export default ({worksData}: Props) => {
  const router = useRouter()

  const initialNumOfPages = getNumOfPages(worksData.length, ITEMPERPAGE)

  const [filterValue, setFilterValue] = useState(FILTERVALUES.ALL)
  const [numOfPages, setNumOfPages] = useState(initialNumOfPages)
  const [currentPage, setCurrentPage] = useState(router.query.page ? Number(router.query.page) : 1)

  useEffect(() => {
    const numOfWorks = filterValue === "#all" ? worksData.length : worksData.filter(workData => workData.tags.includes(filterValue)).length

    const newNumOfPages = getNumOfPages(numOfWorks, ITEMPERPAGE)

    setNumOfPages(newNumOfPages)
  }, [filterValue])

  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    const target = event.target as HTMLButtonElement
    const value = target.value
    setFilterValue(value)
  }

  const handleMovePrev = () => {
    if (currentPage === 1) {
      setCurrentPage(1)
      router.push("/works/?page=1", undefined, {shallow: true})
    } else {
      setCurrentPage(currentPage - 1)
      router.push(`/works/?page=${currentPage - 1}`, undefined, {shallow: true})
    }
  }

  const handleMoveNext = () => {
    if (currentPage === numOfPages) {
      setCurrentPage(numOfPages)
      router.push(`/works/?page=${numOfPages}`, undefined, {shallow: true})
    } else {
      setCurrentPage(currentPage + 1)
      router.push(`/works/?page=${currentPage + 1}`, undefined, {shallow: true})
    }
  }

  const handleMoveToPage = (event: React.MouseEvent<HTMLButtonElement>) => {
    const target = event.target as HTMLButtonElement
    setCurrentPage(parseInt(target.value))
    router.push(`/works/?page=${target.value}`, undefined, {shallow: true})
  }

  const filters = [
    {
      label: "all",
      value: FILTERVALUES.ALL,
    },
    {
      label: "app",
      value: FILTERVALUES.APPS,
    },
    {
      label: "logo",
      value: FILTERVALUES.LOGOS,
    },
    {
      label: "illustration",
      value: FILTERVALUES.ILLUSTRATIONS,
    }
  ]

  return (
    <Layout>
      <Head>
        <title>Works: Jesse Wei</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/global-images/favicon.png" />
      </Head>
      <Header mode="light" />
      <Main className='bg-mute py-36'>
        <div className='container'>
          <h2 className='mb-8'>Works.</h2>
          {filters.map((filter, index) => {
            const {label, value} = filter
            return (
              <FilterButton
                label={label}
                value={value}
                isActive={value === filterValue}
                handleClick={handleClick}
              />
            )
          })}
          {filterValue === "#all" ? (
            <div className='mt-16 lg:grid lg:grid-cols-3 lg:justify-items-stretch lg:gap-x-24 lg:gap-y-20'>
              {worksData.slice(ITEMPERPAGE * (currentPage - 1), ITEMPERPAGE * currentPage).map((workData, index) => {
                return (
                  <Card
                    index={index}
                    itemData={workData}
                    wrapperClassName="w-full"
                    cardClassName="h-full"
                  />
                )
              })}
            </div>
          ) : (
            <div className='mt-16 lg:grid lg:grid-cols-3 lg:justify-items-stretch lg:gap-x-24 lg:gap-y-20'>
              {worksData.filter(workData => workData.tags.includes(filterValue)).slice(ITEMPERPAGE * (currentPage - 1), ITEMPERPAGE * currentPage).map((workData, index) => {
                return (
                  <Card
                    index={index}
                    itemData={workData}
                    wrapperClassName="w-full"
                    cardClassName="h-full"
                  />
                )
              })}
            </div>
          )}
          <Pagination
            numOfPages={numOfPages}
            currentPage={currentPage}
            handleMovePrev={handleMovePrev}
            handleMoveNext={handleMoveNext}
            handleMoveToPage={handleMoveToPage}
          />
        </div>
      </Main>
      <Footer position="static" />
    </Layout>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const worksData = getWorksData()
  return {
    props: {
      worksData
    }
  }
}