import Head from 'next/head'
import {Layout} from '../../components/layout';
import {Header} from '../../components/header'
import {Article} from '../../components/article';
import {getPostIds, getPostContentAndData} from '../../lib/posts'

export default ({postData}: any) => {
  return (
    <Layout>
      <Head>
        <title>{postData.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/global-images/favicon.png" />
      </Head>
      <Header />
      <Article
        postData={postData}
      />
    </Layout>
  )
}

export const getStaticPaths = async () => {
  const paths = getPostIds()
  return {
    paths,
    fallback: true
  }
}

export const getStaticProps = async ({params}: any) => {
  const postData = await getPostContentAndData(params.id)
  return {
    props: {
      postData
    }
  }
}




