import Head from 'next/head'
import {Post, PostDataType} from '../../types'
import {Layout} from '../../components/layout';
import {Header} from '../../components/header'
import {Article} from '../../components/article';
import {Sidebar} from '../../components/sidebar'
import {getPostIds, getPostContentAndData, getPostsData} from '../../lib/posts'

type Props = {
  item: Post
  moreItems: Array<PostDataType>
}

export default ({item, moreItems}: Props) => {
  const {title} = item
  return (
    <Layout>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/global-images/favicon.png" />
      </Head>
      <Header mode="light" />
      <Article
        item={item}
      />
      <Sidebar
        items={moreItems}
      />
    </Layout>
  )
}

export const getStaticPaths = async () => {
  const paths = getPostIds()
  return {
    paths,
    fallback: true
  }
}

export const getStaticProps = async ({params}: any) => {
  const item = await getPostContentAndData(params.id)
  const moreItems = getPostsData((fileName: string) => !fileName.includes(item.id))
  return {
    props: {
      item,
      moreItems
    }
  }
}




