import Head from 'next/head'
import {GetStaticProps} from 'next'
import {getWorksData} from '../lib/works'
import {getPostsData} from '../lib/posts'
import {Layout} from '../components/layout'
import {Header} from '../components/header'
import {Main} from '../components/main'
import {Footer} from '../components/footer'

export default ({worksData, postsData}: any) => {
  return (
    <Layout>
      <Head>
        <title>Jesse Wei: Develop Beautiful & User-friendly Web Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/global-images/favicon.png" />
      </Head>
      <Header mode="primary" />
      <Main
        worksData={worksData}
        postsData={postsData}
      />
      <Footer position='absolute' />
    </Layout>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const worksData = getWorksData()
  const postsData = getPostsData()
  return {
    props: {
      worksData,
      postsData
    }
  }
}
