import Head from 'next/head'
import {GetStaticProps} from 'next'
import {getEntriesData} from '../lib/entries'
import {Layout} from '../components/layout'
import {Header} from '../components/header'
import {FirstView} from '../components/first-view';
import {Expertise} from '../components/expertise';
import {Works} from '../components/works';
import {Posts} from '../components/posts';
import {About} from '../components/about';
import {Contact} from '../components/contact';
import {Main} from '../components/main'
import {Footer} from '../components/footer'

const Home = ({worksData, postsData}: any) => {
  return (
    <Layout>
      <Head>
        <title>Jesse Wei: Develop Beautiful & User-friendly Web Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/global-images/favicon.png" />
      </Head>
      <Header mode="primary" />
      <Main>
        <FirstView />
        <Expertise />
        <Works
          worksData={worksData}
        />
        <Posts
          postsData={postsData}
        />
        <About />
        <Contact />
      </Main>
      <Footer position='absolute' />
    </Layout>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async () => {
  const worksData = getEntriesData("works")
  const postsData = getEntriesData("posts")
  return {
    props: {
      worksData,
      postsData
    }
  }
}
